server :
  prefix : "§l§b[ §l§eOhurjon §l§b] "
reach :
  range : 5.5
  notice : "§l§e{name}§l§f의 이상한 데미지 범위 : §l§e{range}"
  items: ["WOOD_SWORD", "NETHER_STALK", "AIR"]
cps :
  limit : 10
  kick : "이상한 cps 가 감지되어 킥되었습니다. 감지된 cps : {cps}"
  notice : "{name}의 이상한 cps : {cps}"